name = libf3.a

LIBPATH = /usr/local/lib/

SRC = ft_putchar.c\
ex06/ft_print_alphabet.c\

OBJ = $(SRC:.c=.o)

all: $(NAME)

$(NAME):
	gcc -Wall -Wextra -Werror -c $(SRC)
	ar rc $(LIBPATH)$(N    *ft_strupcase(char *str);                                                      
                                                                                        │char    *ft_strrev(char *str);                                                         
#endif                                                                                  │int     ft_str_is_alpha(char *str);                                                    
                                                                                        │int     ft_str_is_numeric(char *str);                                                  
                                                                                        │int     ft_str_is_lowercase(char *str);                                                
                                                                                        │int     ft_str_is_uppercase(char *str);                                                
                                                                                        │int     ft_any(char **tab, int(*f)(char *));                                           
                                                                                        │int     ft_count_if(char **tab, int(*f)(char *));                                      
                                                                                        │       AME

